(() => {
  'use strict';
  const KEY='tradingCapitalTracker.v1';
  const DEFAULT={contributions:[],trades:[],settings:{riskPct:0.5,dailyLossPct:1,capitalCeiling:500}};
  let state=load();
  let deferredPrompt=null;
  const $=id=>document.getElementById(id);
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n)||0);
  const pct=n=>`${(Number(n)||0).toFixed(2)}%`;
  const uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const today=()=>new Date().toISOString().slice(0,10);
  const dateValue=s=>s?new Date(`${s}T12:00:00`).getTime():0;

  function load(){try{const raw=JSON.parse(localStorage.getItem(KEY));return raw&&raw.settings?raw:structuredClone(DEFAULT)}catch{return structuredClone(DEFAULT)}}
  function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
  function contributionTotal(){return state.contributions.reduce((a,c)=>a+Number(c.amount||0),0)}
  function tradePL(t){if(!t.exitPrice||!t.exitDate)return null;return (Number(t.exitPrice)-Number(t.entryPrice))*Number(t.qty)-Number(t.fees||0)}
  function costBasis(t){return Number(t.entryPrice)*Number(t.qty)}
  function proceeds(t){return Number(t.exitPrice||0)*Number(t.qty)-Number(t.fees||0)}
  function statusOf(t){if(!t.exitDate||!t.exitPrice)return 'open';if(t.asset==='Crypto')return 'settled';if(t.settlementDate && t.settlementDate<=today())return 'settled';return 'awaiting'}
  function nextBusinessDay(dateStr){const d=new Date(`${dateStr}T12:00:00`);do{d.setDate(d.getDate()+1)}while(d.getDay()===0||d.getDay()===6);return d.toISOString().slice(0,10)}
  function realizedPL(){return state.trades.reduce((a,t)=>a+(tradePL(t)??0),0)}
  function summary(){
    const contrib=contributionTotal(); let settled=contrib, unsettled=0, open=0;
    for(const t of state.trades){const st=statusOf(t); if(st==='open'){settled-=costBasis(t);open+=costBasis(t)} else if(st==='awaiting'){settled-=costBasis(t);unsettled+=proceeds(t)} else {settled+=tradePL(t)??0}}
    return {contrib,settled,unsettled,open,pl:realizedPL(),capital:contrib+realizedPL()};
  }
  function setPLClass(el,val){el.classList.remove('pos','neg');if(val>0)el.classList.add('pos');if(val<0)el.classList.add('neg')}
  function render(){renderSummary();renderContributions();renderTrades();renderAnalytics();renderStrategies();renderSettings()}
  function renderSummary(){const s=summary();$('capitalValue').textContent=money(s.capital);$('settledCash').textContent=money(s.settled);$('unsettledCash').textContent=money(s.unsettled);$('openBasis').textContent=money(s.open);$('realizedPL').textContent=money(s.pl);setPLClass($('realizedPL'),s.pl);$('returnPct').textContent=pct(s.contrib?100*s.pl/s.contrib:0);setPLClass($('returnPct'),s.pl);const maxTrade=s.capital*state.settings.riskPct/100,maxDay=s.capital*state.settings.dailyLossPct/100;$('maxRiskTrade').textContent=money(maxTrade);$('maxRiskDay').textContent=money(maxDay);const tpl=state.trades.filter(t=>t.exitDate===today()).reduce((a,t)=>a+(tradePL(t)??0),0);$('todayPL').textContent=money(tpl);setPLClass($('todayPL'),tpl);const warn=$('dailyWarning');if(tpl<=-maxDay && maxDay>0){warn.textContent=`Daily loss limit reached: ${money(tpl)} versus your ${money(maxDay)} limit.`;warn.classList.remove('hidden')}else warn.classList.add('hidden')}
  function renderContributions(){const tb=$('contributionRows');tb.innerHTML='';[...state.contributions].sort((a,b)=>dateValue(b.date)-dateValue(a.date)).forEach(c=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${c.date}</td><td>${money(c.amount)}</td><td>${esc(c.note||'')}</td><td><button class="link-delete" data-contribution="${c.id}">Delete</button></td>`;tb.appendChild(tr)});tb.querySelectorAll('[data-contribution]').forEach(b=>b.onclick=()=>{if(confirm('Delete this contribution?')){state.contributions=state.contributions.filter(c=>c.id!==b.dataset.contribution);save()}})}
  function filteredTrades(){const a=$('filterAsset').value,s=$('filterStatus').value,q=$('filterSymbol').value.trim().toUpperCase();return [...state.trades].filter(t=>(a==='all'||t.asset===a)&&(s==='all'||statusOf(t)===s)&&(!q||t.symbol.includes(q))).sort((x,y)=>dateValue(y.entryDate)-dateValue(x.entryDate))}
  function renderTrades(){const tb=$('tradeRows');tb.innerHTML='';const list=filteredTrades();$('emptyTrades').classList.toggle('hidden',list.length>0);for(const t of list){const pl=tradePL(t),st=statusOf(t);const tr=document.createElement('tr');tr.innerHTML=`<td>${t.entryDate}</td><td><strong>${esc(t.symbol)}</strong></td><td>${t.asset}</td><td>${fmt(t.qty)}</td><td>${money(t.entryPrice)}</td><td>${t.exitPrice?money(t.exitPrice):'—'}</td><td>${t.stop?money(t.stop):'—'}</td><td>${t.target?money(t.target):'—'}</td><td class="${pl>0?'pos':pl<0?'neg':''}">${pl===null?'—':money(pl)}</td><td><span class="status">${st==='open'?'Open':st==='awaiting'?'Awaiting':'Settled'}</span></td><td>${t.settlementDate||'—'}</td><td><div class="row-actions"><button data-edit="${t.id}">Edit</button><button data-delete="${t.id}">Delete</button></div></td>`;tb.appendChild(tr)}tb.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openTrade(state.trades.find(t=>t.id===b.dataset.edit)));tb.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Delete this trade?')){state.trades=state.trades.filter(t=>t.id!==b.dataset.delete);save()}})}
  function renderSettings(){$('riskPct').value=state.settings.riskPct;$('dailyLossPct').value=state.settings.dailyLossPct;$('capitalCeiling').value=state.settings.capitalCeiling}
  function closed(){return state.trades.filter(t=>tradePL(t)!==null)}
  function renderAnalytics(){const c=closed(),wins=c.filter(t=>tradePL(t)>0),loss=c.filter(t=>tradePL(t)<0);$('closedTrades').textContent=c.length;$('winRate').textContent=pct(c.length?100*wins.length/c.length:0);$('avgWin').textContent=money(wins.length?wins.reduce((a,t)=>a+tradePL(t),0)/wins.length:0);$('avgLoss').textContent=money(loss.length?loss.reduce((a,t)=>a+tradePL(t),0)/loss.length:0);const gp=wins.reduce((a,t)=>a+tradePL(t),0),gl=Math.abs(loss.reduce((a,t)=>a+tradePL(t),0));$('profitFactor').textContent=gl? (gp/gl).toFixed(2):(gp>0?'∞':'—');const ordered=[...c].sort((a,b)=>dateValue(a.exitDate)-dateValue(b.exitDate));let equity=0,peak=0,dd=0;for(const t of ordered){equity+=tradePL(t);peak=Math.max(peak,equity);dd=Math.max(dd,peak-equity)}$('maxDrawdown').textContent=money(dd)}
  function renderStrategies(){const map={};for(const t of closed()){const k=(t.strategy||'Unspecified').trim()||'Unspecified';if(!map[k])map[k]={n:0,w:0,pl:0};map[k].n++;const p=tradePL(t);if(p>0)map[k].w++;map[k].pl+=p}const tb=$('strategyRows');tb.innerHTML='';Object.entries(map).sort((a,b)=>b[1].pl-a[1].pl).forEach(([k,v])=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${esc(k)}</td><td>${v.n}</td><td>${pct(100*v.w/v.n)}</td><td class="${v.pl>0?'pos':v.pl<0?'neg':''}">${money(v.pl)}</td>`;tb.appendChild(tr)});if(!Object.keys(map).length){const tr=document.createElement('tr');tr.innerHTML='<td colspan="4" class="muted">Close trades to build strategy statistics.</td>';tb.appendChild(tr)}}
  function fmt(n){return Number(n).toLocaleString(undefined,{maximumFractionDigits:8})}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function openContribution(){$('contribDate').value=today();$('contribAmount').value=500;$('contribNote').value='Monthly contribution';$('contributionDialog').showModal()}
  function openTrade(t=null){$('tradeForm').reset();$('editTradeId').value=t?.id||'';$('tradeDialogTitle').textContent=t?'Edit trade':'Add trade';$('tradeDate').value=t?.entryDate||today();$('tradeSymbol').value=t?.symbol||'';$('tradeAsset').value=t?.asset||'Stock';$('tradeStrategy').value=t?.strategy||'';$('tradeQty').value=t?.qty||'';$('tradeEntry').value=t?.entryPrice||'';$('tradeStop').value=t?.stop||'';$('tradeTarget').value=t?.target||'';$('tradeExitDate').value=t?.exitDate||'';$('tradeExit').value=t?.exitPrice||'';$('tradeSettlement').value=t?.settlementDate||'';$('tradeFees').value=t?.fees||0;$('tradeNotes').value=t?.notes||'';$('tradeValidation').classList.add('hidden');$('tradeDialog').showModal()}
  function validateTrade(t,editingId=''){const s=summary();const existing=editingId?state.trades.find(x=>x.id===editingId):null;let adjustedSettled=s.settled;if(existing&&statusOf(existing)==='open')adjustedSettled+=costBasis(existing);const cost=costBasis(t);if(!editingId && !t.exitDate && cost>adjustedSettled+.005)return `This open position costs ${money(cost)}, but only ${money(adjustedSettled)} is currently shown as settled cash.`;const ceiling=Number(state.settings.capitalCeiling||0);if(ceiling>0&&cost>ceiling+.005)return `Position value ${money(cost)} exceeds your authorized capital ceiling of ${money(ceiling)}.`;if(t.stop){const planned=Math.abs(Number(t.entryPrice)-Number(t.stop))*Number(t.qty);const max=s.capital*state.settings.riskPct/100;if(planned>max+.005)return `Planned stop risk is ${money(planned)}, above your per-trade limit of ${money(max)}.`}return ''}
  $('addContributionBtn').onclick=openContribution;
  $('addTradeBtn').onclick=()=>openTrade();
  $('saveContribution').onclick=e=>{e.preventDefault();const amount=Number($('contribAmount').value);if(!(amount>0))return;state.contributions.push({id:uid(),date:$('contribDate').value,amount,note:$('contribNote').value.trim()});$('contributionDialog').close();save()};
  $('saveTrade').onclick=e=>{e.preventDefault();const asset=$('tradeAsset').value,exitDate=$('tradeExitDate').value;const t={id:$('editTradeId').value||uid(),entryDate:$('tradeDate').value,symbol:$('tradeSymbol').value.trim().toUpperCase(),asset,strategy:$('tradeStrategy').value.trim(),qty:Number($('tradeQty').value),entryPrice:Number($('tradeEntry').value),stop:Number($('tradeStop').value)||0,target:Number($('tradeTarget').value)||0,exitDate,exitPrice:Number($('tradeExit').value)||0,settlementDate:$('tradeSettlement').value,fees:Number($('tradeFees').value)||0,notes:$('tradeNotes').value.trim()};if(exitDate&&t.exitPrice&&asset!=='Crypto'&&!t.settlementDate)t.settlementDate=nextBusinessDay(exitDate);if(exitDate&&asset==='Crypto')t.settlementDate=exitDate;const msg=validateTrade(t,$('editTradeId').value);if(msg){$('tradeValidation').textContent=msg;$('tradeValidation').classList.remove('hidden');return}const i=state.trades.findIndex(x=>x.id===t.id);if(i>=0)state.trades[i]=t;else state.trades.push(t);$('tradeDialog').close();save()};
  $('saveSettings').onclick=()=>{state.settings.riskPct=Math.max(.01,Number($('riskPct').value)||.5);state.settings.dailyLossPct=Math.max(.01,Number($('dailyLossPct').value)||1);state.settings.capitalCeiling=Math.max(0,Number($('capitalCeiling').value)||0);save()};
  $('refreshSettlementBtn').onclick=()=>{save()};
  ['filterAsset','filterStatus','filterSymbol'].forEach(id=>$(id).addEventListener(id==='filterSymbol'?'input':'change',renderTrades));
  $('calcPosition').onclick=()=>{const entry=Number($('calcEntry').value),stop=Number($('calcStop').value),risk=Math.abs(entry-stop),s=summary(),budget=s.capital*state.settings.riskPct/100,ceiling=Number(state.settings.capitalCeiling||Infinity);if(!(entry>0)||!(stop>0)||risk<=0){$('calcNote').textContent='Enter different positive entry and stop prices.';return}let shares=Math.floor(budget/risk);shares=Math.min(shares,Math.floor(s.settled/entry),Math.floor(ceiling/entry));shares=Math.max(0,shares);$('calcRiskShare').textContent=money(risk);$('calcShares').textContent=shares;$('calcPositionValue').textContent=money(shares*entry);$('calcNote').textContent=shares?`At ${fmt(shares)} shares, planned stop risk is about ${money(shares*risk)}.`:'Your current cash/risk settings do not support a whole-share position at this price.'};
  function download(name,type,text){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
  $('exportJson').onclick=()=>download(`trading-tracker-backup-${today()}.json`,'application/json',JSON.stringify(state,null,2));
  $('exportCsv').onclick=()=>{const rows=[['Entry Date','Symbol','Asset','Strategy','Quantity','Entry Price','Stop','Target','Exit Date','Exit Price','Settlement Date','Fees','Realized P/L','Status','Notes'],...state.trades.map(t=>[t.entryDate,t.symbol,t.asset,t.strategy,t.qty,t.entryPrice,t.stop||'',t.target||'',t.exitDate||'',t.exitPrice||'',t.settlementDate||'',t.fees||0,tradePL(t)??'',statusOf(t),t.notes||''])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');download(`trades-${today()}.csv`,'text/csv',csv)};
  $('importJson').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const data=JSON.parse(await f.text());if(!data||!Array.isArray(data.contributions)||!Array.isArray(data.trades)||!data.settings)throw new Error();if(confirm('Replace current local data with this backup?')){state=data;save()}}catch{alert('That file is not a valid Trading Capital Tracker backup.')}finally{e.target.value=''}};
  $('resetData').onclick=()=>{if(confirm('Reset all app data? This cannot be undone unless you have an exported backup.')){state=structuredClone(DEFAULT);localStorage.removeItem(KEY);save()}};
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});
  $('installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden')};
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
  if(!state.contributions.length){state.contributions.push({id:uid(),date:today(),amount:500,note:'Initial trading capital'});save()}else render();
})();
